# Generated by Django 4.0.2 on 2022-07-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='images', verbose_name='Image')),
            ],
        ),
    ]
