# Generated by Django 4.0.2 on 2022-07-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
